spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drools_db_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  level:
    com.example.drools: DEBUG
    org.drools: DEBUG